---
- name: "Playbook to upgrade CaC from AAP <= 2.4 to AAP >= 2.5 format"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    personal_access_token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') }}"
    software_repository: https://{{ personal_access_token }}@github.com/taiseerhussein/export-import-aap-assets.git
    local_repo: /var/tmp/github/aap24_configs
    git_name: taiseerhussein
    git_email: tkhussein@yahoo.com

    flatten: true
    filetree_read_organizations: false
    input_path: "{{ local_repo }}/{{ aap24_configs }}"
    gateway_validate_certs: false
    controller_host: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
    controller_username: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
    controller_password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"

    
    aap_hostname: "https://ec2-13-59-192-24.us-east-2.compute.amazonaws.com"
    aap_username: admin
    aap_password: "{{ aap_admin_password }}"
    aap_token: "{{ aap_token }}"
    aap_validate_certs: false
    aap_request_timeout: 30

  pre_tasks:
    - name: Check credential type data
      ansible.builtin.debug:
        var: controller_credential_types
  roles:
    - ../../roles/prep-env-2.7
    - ../../roles/manage-aap-config-2.7
    
    - role: infra.aap_configuration.controller_credential_types
      vars: 
        aap_request_timeout: 30
      when: controller_credential_types is defined

    - role: infra.aap_configuration.controller_credentials
      vars: 
        aap_request_timeout: 30
      when: controller_credentials is defined