---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-26/ee-supported-rhel9:latest

dependencies:
  galaxy: requirements.yml
  system:
    - systemd-devel
    - pkgconf-pkg-config
    - gcc
    - python3.12-devel
additional_build_files:
  - src: ansible.cfg
    dest: configs
additional_build_steps:
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
options:
  package_manager_path: /usr/bin/microdnf
