---
controller_applications:
  - name: "app-1-demo"
    description: ""
    organization: "Default"
    authorization_grant_type: "authorization-code"
    redirect_uris: "https://192.168.65.4"
    skip_authorization: "False"
    client_type: "confidential"
  - name: "demo3"
    description: ""
    organization: "Default"
    authorization_grant_type: "authorization-code"
    redirect_uris: "https://192.168.65.4/"
    skip_authorization: "False"
    client_type: "confidential"
  - name: "aap-2-demo"
    description: ""
    organization: "dev"
    authorization_grant_type: "password"
    redirect_uris: "https://192.168.65.4"
    skip_authorization: "False"
    client_type: "confidential"
...
